# SPDX-License-Identifier: Apache-2.0
"""
Abstract persistence protocols for hotframe.

These Protocol classes define the interface that the persistence layer
must satisfy. The default implementation is SQLAlchemy (AsyncSession,
HubQuery, BaseRepository), but any backend that satisfies these
protocols can be used.

Usage::

    from hotframe import ISession, IQueryBuilder, IRepository

    class MyService:
        def __init__(self, db: ISession, hub_id: UUID) -> None: ...
"""

from __future__ import annotations

from collections.abc import Sequence
from decimal import Decimal
from typing import Any, Protocol, Self
from uuid import UUID


class IScalarResult[T_co](Protocol):
    """Result of scalars() — iterable of single-column values."""

    def all(self) -> list[T_co]: ...
    def first(self) -> T_co | None: ...


class IExecuteResult(Protocol):
    """Result of session.execute() — wraps a cursor/result set."""

    def scalars(self) -> IScalarResult[Any]: ...
    def scalar_one(self) -> Any: ...
    def scalar_one_or_none(self) -> Any | None: ...
    def first(self) -> Any | None: ...
    def all(self) -> list[Any]: ...


class ISession(Protocol):
    """Abstract async database session."""

    async def execute(self, statement: Any, parameters: Any = None) -> IExecuteResult: ...
    def add(self, instance: Any) -> None: ...
    async def flush(self, objects: Any = None) -> None: ...
    async def rollback(self) -> None: ...
    async def commit(self) -> None: ...
    async def delete(self, instance: Any) -> None: ...
    def in_transaction(self) -> bool: ...
    def begin(self) -> Any: ...
    def begin_nested(self) -> Any: ...


class IQueryBuilder[T](Protocol):
    """Abstract chainable async query builder."""

    def filter(self, *conditions: Any) -> Self: ...
    def order_by(self, *columns: Any) -> Self: ...
    def options(self, *opts: Any) -> Self: ...
    def limit(self, n: int) -> Self: ...
    def offset(self, n: int) -> Self: ...
    def with_deleted(self) -> Self: ...
    async def all(self) -> list[T]: ...
    async def first(self) -> T | None: ...
    async def get(self, id: UUID) -> T | None: ...
    async def count(self) -> int: ...
    async def sum(self, column: Any) -> Decimal: ...
    async def exists(self) -> bool: ...
    async def get_or_create(self, **defaults: Any) -> tuple[T, bool]: ...
    async def delete(self, id: UUID) -> bool: ...
    async def hard_delete(self, id: UUID) -> bool: ...


class IRepository[T](Protocol):
    """Abstract typed CRUD repository."""

    async def list(
        self,
        *,
        search: str | None = None,
        order_by: Any | None = None,
        limit: int = 50,
        offset: int = 0,
        options: Sequence[Any] | None = None,
        **filters: Any,
    ) -> dict[str, Any]: ...
    async def get(self, id: UUID, *, options: Sequence[Any] | None = None) -> T | None: ...
    async def create(self, **kwargs: Any) -> T: ...
    async def update(self, id: UUID, **kwargs: Any) -> T | None: ...
    async def delete(self, id: UUID) -> bool: ...
    async def hard_delete(self, id: UUID) -> bool: ...
    async def count(self, **filters: Any) -> int: ...
    async def exists(self, **filters: Any) -> bool: ...
